### ISSUE TITLE
Need more contributors for growth of repo :(

### ISSUE THREAD

**Issue by AkkiBond** [AkkiBond/DSALGO#1]
Add Algos or problems whatever you have to contribute.

**Comment by priyamm** [comment]
@AkkiBond I can collaborate.

**Comment by abhidesh007** [comment]
I can do it

**Comment by anmolagarwal999** [comment]
Can I add my implementation of Russian Paesant algo ?

**Comment by AkkiBond** [comment]
Yes but remember formatting the path to which this problem belongs.

**Comment by 17-Vishal** [comment]
Can i be a join ?

**Comment by 17-Vishal** [comment]
Can I join ?

**Comment by 17-Vishal** [comment]
Can I join ?
