### ISSUE TITLE
Can Add Dynamic Programming Folder.

### ISSUE THREAD

**Issue by sagar-barapatre** [AkkiBond/DSALGO#53]
I can create the dynamic programming folder that contains all the standard questions of Dynamic programming from Leetcode as well as Interview Bit

**Comment by AkkiBond** [comment]
Yes you can do that. Just PR after doing this I'll approve that.

**Comment by sagar-barapatre** [comment]
#54

**Comment by AkkiBond** [comment]
Thank you for you contribution. Don't forget to contribute in Hacktoberfest ;)
